name: Visitor Badge
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Update Visitor Count
        uses: absamer/visitor-badge@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME: visitors.json
